environment:
  HIP_VISIBLE_DEVICES: '0'
  VLLM_USE_TRITON_FLASH_ATTN: '0'
vllm_config:
  api_key: abc-123
  model_id: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  port: 8000
  served_model_name: deepseek-r1-distill-qwen-32b
  tp: 8
